# Generated by Django 4.2.16 on 2024-10-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(default='welcome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
