# Generated by Django 5.1.1 on 2024-10-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='external_id',
            field=models.IntegerField(null=True),
        ),
    ]
